on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 500
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 500
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install LLVM
        if: matrix.os == 'windows-latest'
        run: choco install -y llvm
      - name: Setup msbuild
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1
      - uses: actions-rs/cargo@v1
        timeout-minutes: 20
        if: matrix.os == 'windows-latest'
        env:
          LIBCLANG_PATH: "C:\\Program Files\\LLVM\\bin"
        with:
          command: test
      - uses: actions-rs/cargo@v1
        if: matrix.os != 'windows-latest'
        with:
          command: test
      - name: Test package mupdf-sys
        uses: actions-rs/cargo@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          command: package
          args: --manifest-path mupdf-sys/Cargo.toml

  asan:
    name: Address Sanitizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 500
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: -Z sanitizer=address

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
